services:
  web:
    build: .
    depends_on:
      - db

    environment:
      - HOST=db
      - USER=odoo
      - PASSWORD=odoo
      - DB_NAME=hbisono_final
    ports:
      - 8069:8069


    command: >
      sh -c "odoo --db_host=db --db_user=odoo --db_password=odoo -d hbisono_final -i account --without-demo=all --stop-after-init; 
             echo \"c=env['res.company'].browse(1); c.write({'name': 'Hnos Bisonó', 'vat': '130836345', 'country_id': env.ref('base.do').id, 'currency_id': env.ref('base.DOP').id}); env['account.chart.template'].try_loading('do', c); env['ir.config_parameter'].sudo().set_param('report.url', 'http://localhost:8069'); admin=env.ref('base.user_admin'); admin.write({'groups_id': [(4, g.id) for g in env['res.groups'].search([]) if g.category_id.xml_id in ('base.module_category_accounting_accounting', 'base.module_category_accounting_invoicing')]}); env['res.lang']._activate_lang('es_DO'); env['res.users'].search([]).write({'lang': 'es_DO'}); env['res.partner'].search([]).write({'lang': 'es_DO'}); env['res.company'].search([('id', '!=', 1)]).write({'active': False}); env['account.journal'].search([('company_id', '=', 1), ('type', 'in', ('sale', 'purchase'))]).write({'l10n_latam_use_documents': True}); env.cr.commit()\" | odoo shell -d hbisono_final --db_host=db --db_user=odoo --db_password=odoo --no-http --stop-after-init; 
             odoo --addons-path=/usr/lib/python3/dist-packages/odoo/addons,/mnt/extra-addons --db_host=db --db_user=odoo --db_password=odoo -d hbisono_final --load-language=es_DO --without-demo=all -i l10n_do_accounting --stop-after-init && 
             odoo --addons-path=/usr/lib/python3/dist-packages/odoo/addons,/mnt/extra-addons --db_host=db --db_user=odoo --db_password=odoo -d hbisono_final -u l10n_do_accounting"












    volumes:
      - odoo-data:/var/lib/odoo

  db:
    image: postgres:15
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - odoo-db-data:/var/lib/postgresql/data/pgdata

volumes:
  odoo-db-data:
  odoo-data:

